<?php

return [
    'banks' => [
        'Access Bank Plc',
        'Accion Microfinance Bank',
        'Advans La Fayette Microfinance Bank',
        'Citibank Nigeria Limited',
        'Coronation Merchant Bank',
        'Covenant Microfinance Bank Ltd',
        'Ecobank Nigeria',
        'Empire Trust Microfinance Bank',
        'Fidelity Bank Plc',
        'Fina Trust Microfinance Bank',
        'FBNQuest Merchant Bank',
        'First Bank of Nigeria Limited',
        'First City Monument Bank Limited',
        'Finca Microfinance Bank Limited',
        'Globus Bank Limited',
        'Guaranty Trust Holding Company Plc',
        'Heritage Bank Plc',
        'Infinity Microfinance Bank',
        'Jaiz Bank Plc',
        'Keystone Bank Limited',
        'LOTUS BANK',
        'Mint Finex MFB',
        'Mkobo MFB',
        'Mutual Trust Microfinance Bank',
        'Nova Merchant Bank',
        'Opay Digital Bank',
        'Optimus Bank Limited',
        'Palmpay',
        'Parallex Bank Limited',
        'Peace Microfinance Bank',
        'Pearl Microfinance Bank Limited',
        'Polaris Bank Limited',
        'PremiumTrust Bank Limited',
        'Providus Bank Limited',
        'Rand Merchant Bank',
        'Raven Bank',
        'Rephidim Microfinance Bank',
        'Rex Microfinance Bank',
        'Rubies Bank',
        'Sparkle Bank',
        'Stanbic IBTC Bank Plc',
        'Standard Chartered',
        'Sterling Bank Plc',
        'SunTrust Bank Nigeria Limited',
        'TAJBank Limited',
        'Titan Trust Bank',
        'Union Bank of Nigeria Plc',
        'United Bank for Africa Plc',
        'VFD Microfinance Bank',
        'Wema Bank Plc',
        'Zenith Bank Plc',
    ],
];

